# Generated by Django 2.0.8 on 2018-08-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exer3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='group',
            new_name='Class_Section',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='person',
            new_name='Student_Name',
        ),
    ]
